export enum MetodoPrediccion{
    PROMEDIO_MOVIL_PONDERADO = "PROMEDIO_MOVIL_PONDERADO",
    PROMEDIO_MOVIL_SUAVIZADO = 'PROMEDIO_MOVIL_SUAVIZADO',
    REGRESION_LINEAL = 'REGRESION_LINEAL',
    ESTACIONALIDAD = 'ESTACIONALIDAD',
}